kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "liberty-pipeline-ci-cd"
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: openshift/Jenkinsfile
      env:
        - name: DEV_PROJECT 
          value: ci-development
        - name: STAGE_PROJECT
          value: ci-development
        - name: PROD_PROJECT
          value: ci-development
        - name: APP_NAME
          value: simple-liberty-app
  source:
    type: Git
    git:
      uri: 'https://eu-gb.git.cloud.ibm.com/vlad.sancira/simple-liberty-app.git'
  triggers:
    - type: GitLab
      gitlab:
        secretReference:
          name: gitlabkey
