apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: liberty-pipeline
spec:
  resources:
    - name: liberty-git
      type: git
    - name: liberty-image
      type: image
  
  tasks:
    - name: build
      taskRef:
        name: build-liberty-app
      resources:
        inputs:
          - name: source
            resource: liberty-git
        outputs:
          - name: image
            resource: liberty-image

    - name: deploy
      taskRef:
        name: deploy-liberty-app
      runAfter:
        - build
      resources:
        inputs:
          - name: source
            resource: liberty-git