apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: liberty-pipeline
spec:
  resources:
    - name: liberty-git
      type: git
    - name: liberty-image
      type: image

  params:
    - name: DEPLOY_ENVIRONMENT
      description: The environment where you deploy the app
      default: 'env-dev'
  
  tasks:
    - name: build
      taskRef:
        name: build-liberty-app
      resources:
        inputs:
          - name: source
            resource: liberty-git
        outputs:
          - name: image
            resource: liberty-image

    - name: deploy
      taskRef:
        name: deploy-liberty-app
      runAfter:
        - build
      params:
        - name: DEPLOY_ENVIRONMENT
          value: "$(params.DEPLOY_ENVIRONMENT)"
      resources:
        inputs:
          - name: source
            resource: liberty-git