apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: liberty-pipeline-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: liberty-pipeline-trigger
      bindings:
        - name: liberty-pipeline-binding
      template:
        name: liberty-pipeline-template
---

apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: liberty-pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
---

apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: liberty-pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: liberty-pipeline-run
      spec:
        pipelineRef:
          name: liberty-pipeline
        resources:
          - name: liberty-git
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(params.gitrevision)
                - name: url
                  value: $(params.gitrepositoryurl)
          - name: liberty-image
            resourceRef:
              name: liberty-image
---

apiVersion: v1
kind: Service
metadata:
  name: liberty-pipeline-listener
  labels:
    app: liberty-pipeline-listener
spec:
  type: NodePort
  ports:
    - port: 8080
      name: liberty-pipeline-listener
      nodePort: 32429
  selector:
    app: liberty-pipeline-listener