apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: liberty-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://eu-gb.git.cloud.ibm.com/vlad.sancira/simple-liberty-app.git

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: liberty-image
spec:
  type: image
  params:
    - name: url
      value: us.icr.io/cloud-images/liberty-app:latest