apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-run-sa
secrets:
- name: ibm-cr-secret
---

apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token