apiVersion: v1
kind: Secret
metadata:
  name: githubsecret
type: Opaque
stringData:
  secretToken: "1234567"
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
secrets:
  - name: githubsecret
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-minimal
rules:
  # Permissions for every EventListener deployment to function
  - apiGroups: ["tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"] # secrets are only needed for Github/Gitlab interceptors
    verbs: ["get", "list", "watch"]
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-binding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-minimal