apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-trigger-sa
secrets:
- name: ibm-cr-secret
---

apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  annotations:
    kubernetes.io/service-account.name: pipeline-trigger-sa
type: kubernetes.io/service-account-token