apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
secrets:
- name: ibm-cr-secret
---

apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  annotations:
    kubernetes.io/service-account.name: tekton-triggers-sa
type: kubernetes.io/service-account-token
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: tekton-pipelines
  name: tekton-triggers-minimal
rules:
  # Permissions for every EventListener deployment to function
  - apiGroups: ["tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"] # secrets are only needed for Github/Gitlab interceptors
    verbs: ["get", "list", "watch"]
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create"]
  # Pipelines Permissions
  - apiGroups: ["extensions", "apps", ""]
    resources: ["services", "deployments", "pods"]
    verbs: ["get", "create", "update", "patch", "list", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-minimal
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
    namespace: tekton-pipelines